version: '3'
services:
  workspace:
    image: harbor.oneitfarm.com/deployv2/workspace:php-7.1
    restart: always
    volumes:
      - ./:/opt/ci123/www/html
    env_file:
      - docker.env
  lnmp:
    build:
      context: ./docker/lnmp
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/opt/ci123/www/html
    env_file:
      - docker.env
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7.22
    restart: always
    volumes:
      - ./storage/app/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=deploy
  redis:
    image: redis:4.0.10-alpine
    restart: always
    volumes:
      - ./storage/app/redis:/data
    ports:
      - 6379:6379
